language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
before_install:
  cd react
install:
  npm install 
script:
  npm test
notifications:
    slack: co600project:Bskp23tcCyS4znC1HJqQROW3
